# -*- coding: utf-8 -*-
"""titanic data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqCIx1WL3dJuPbPJip3UtPe6OjO_hybC
"""

# Import the Google Drive library from Colab
from google.colab import drive
# Mount Google Drive to access files
drive.mount('/content/drive')

# Data Manipulation and Analysis Libraries
import pandas as pd  # For data manipulation and analysis
import numpy as np   # For numerical computations

# Data Visualization Libraries
import matplotlib.pyplot as plt  # For data visualization and plotting
import seaborn as sns  # For enhanced data visualizations

# Machine Learning Utilities
from sklearn.model_selection import train_test_split  # For splitting dataset into training and testing sets
from sklearn.preprocessing import StandardScaler, LabelEncoder  # For feature scaling and encoding categorical variables

# Model Evaluation Metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  # For model evaluation

# Machine Learning Algorithms
from sklearn.tree import DecisionTreeClassifier  # Decision Tree model for classification tasks
from sklearn.neighbors import KNeighborsClassifier  # K-Nearest Neighbors model for classification tasks

# Import the files library from Google Colab
from google.colab import files

# Upload files from your local machine to Google Colab
# A file upload widget will appear when this code runs
uploaded = files.upload()

# The uploaded files will be saved in the current working directory (/content)

# Load the Titanic dataset into a pandas DataFrame
# Ensure that 'train.csv' is uploaded or located in the correct directory
train_df = pd.read_csv('train.csv')

# Display the first few rows of the dataset to get an overview
print("First 5 rows of the dataset:")
print(train_df.head())

# Display dataset metadata
# This includes column names, non-null counts, and data types
print("\nDataset Information:")
print(train_df.info())

# Display the number of missing values in each column
print("\nMissing Values in Each Column:")
print(train_df.isnull().sum())

# Fill Missing Values

# Fill missing values in 'Age' with the median value (robust against outliers)
train_df['Age'].fillna(train_df['Age'].median(), inplace=True)

# Fill missing values in 'Embarked' with the most frequent value (mode)
train_df['Embarked'].fillna(train_df['Embarked'].mode()[0], inplace=True)

# Drop 'Cabin' column due to excessive missing values
# Too many missing values make imputation unreliable
train_df.drop(columns=['Cabin'], inplace=True)

# Verify if there are any remaining missing values
print("\nRemaining Missing Values After Preprocessing:")
print(train_df.isnull().sum())

# Encode Categorical Columns

# Map 'Sex' column to numerical values
# Male → 1, Female → 0
train_df['Sex'] = train_df['Sex'].map({'male': 1, 'female': 0})

# Map 'Embarked' column to numerical values
# S (Southampton) → 0, C (Cherbourg) → 1, Q (Queenstown) → 2
train_df['Embarked'] = train_df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

# Verify the encoding
print("\nUnique Values After Encoding:")
print("Sex Column:", train_df['Sex'].unique())
print("Embarked Column:", train_df['Embarked'].unique())

# Define Features (Independent Variables) and Target (Dependent Variable)

# Select relevant features for model training
X = train_df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

# Define the target variable (Survived column)
y = train_df['Survived']

# Split the data into Training and Testing sets
# test_size=0.2 → 20% data will be used for testing, 80% for training
# random_state=42 → Ensures reproducibility of results
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display dataset shapes
print("\nDataset Shapes:")
print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)
print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)

# Standardize the Data

# Initialize StandardScaler to standardize numerical features
# It ensures features have a mean of 0 and a standard deviation of 1
scaler = StandardScaler()

# Fit the scaler on the training data and transform it
X_train = scaler.fit_transform(X_train)

# Transform the testing data using the same scaler
X_test = scaler.transform(X_test)

# Verify the transformation (optional)
print("\nData Standardization Complete")
print("First 5 rows of Standardized Training Data:")
print(X_train[:5])

# Train Decision Tree model
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

# Predict with Decision Tree
y_pred_dt = dt_model.predict(X_test)

# Evaluate Decision Tree
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("Classification Report:\n", classification_report(y_test, y_pred_dt))

from sklearn.neighbors import KNeighborsClassifier

# Train KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Predict with KNN
y_pred_knn = knn_model.predict(X_test)

# Evaluate KNN
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))

# Comparison of Model Accuracy
accuracy_dt = accuracy_score(y_test, y_pred_dt)
accuracy_knn = accuracy_score(y_test, y_pred_knn)

models = ['Decision Tree', 'KNN']
accuracy_scores = [accuracy_dt, accuracy_knn]

plt.bar(models, accuracy_scores)
plt.title('Model Accuracy Comparison')
plt.xlabel('Model')
plt.ylabel('Accuracy')
plt.show()

from sklearn.metrics import roc_curve, auc
# Decision Tree ROC
fpr_dt, tpr_dt, _ = roc_curve(y_test, dt_model.predict_proba(X_test)[:,1])
roc_auc_dt = auc(fpr_dt, tpr_dt)
# KNN ROC
fpr_knn, tpr_knn, _ = roc_curve(y_test, knn_model.predict_proba(X_test)[:,1])
roc_auc_knn = auc(fpr_knn, tpr_knn)
# Plot ROC Curves
plt.figure()
plt.plot(fpr_dt, tpr_dt, color='blue', lw=2, label='Decision Tree (area = %0.2f)' % roc_auc_dt)
plt.plot(fpr_knn, tpr_knn, color='red', lw=2, label='KNN (area = %0.2f)' % roc_auc_knn)
plt.plot([0, 1], [0, 1], color='gray', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend(loc="lower right")
plt.show()

from sklearn.metrics import confusion_matrix

# Decision Tree Confusion Matrix
confusion_matrix_dt = confusion_matrix(y_test, y_pred_dt)

# KNN Confusion Matrix
confusion_matrix_knn = confusion_matrix(y_test, y_pred_knn)

import seaborn as sns
import matplotlib.pyplot as plt

# Plot Confusion Matrix for Decision Tree
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.heatmap(confusion_matrix_dt, annot=True, cmap='Blues', fmt='g')
plt.title('Decision Tree Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')

# Plot Confusion Matrix for KNN
plt.subplot(1, 2, 2)
sns.heatmap(confusion_matrix_knn, annot=True, cmap='Greens', fmt='g')
plt.title('KNN Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report

# Print Classification Report for Decision Tree
print("Decision Tree Classification Report:\n", classification_report(y_test, y_pred_dt))

# Print Classification Report for KNN
print("KNN Classification Report:\n", classification_report(y_test, y_pred_knn))

# Get Probability Predictions for Decision Tree and KNN
y_proba_dt = dt_model.predict_proba(X_test)[:, 1]  # Probability of class 1 (Survived)
y_proba_knn = knn_model.predict_proba(X_test)[:, 1]  # Probability of class 1 (Survived)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Calculate ROC curve for Decision Tree
fpr_dt, tpr_dt, _ = roc_curve(y_test, y_proba_dt)
roc_auc_dt = auc(fpr_dt, tpr_dt)

# Calculate ROC curve for KNN
fpr_knn, tpr_knn, _ = roc_curve(y_test, y_proba_knn)
roc_auc_knn = auc(fpr_knn, tpr_knn)

# Plot ROC Curves
plt.figure(figsize=(10, 6))
plt.plot(fpr_dt, tpr_dt, label='Decision Tree (AUC = {:.2f})'.format(roc_auc_dt))
plt.plot(fpr_knn, tpr_knn, label='KNN (AUC = {:.2f})'.format(roc_auc_knn))
plt.plot([0, 1], [0, 1], linestyle='--', color='grey')
plt.title('ROC Curve Comparison')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend()
plt.show()

# Feature Importance for Decision Tree
importances = dt_model.feature_importances_
feature_names = X.columns

plt.figure(figsize=(10, 6))
sns.barplot(x=importances, y=feature_names)
plt.title('Feature Importance (Decision Tree)')
plt.show()